import { useEffect } from 'react'
import { Link, useParams } from 'react-router'
import { ArrowRight, BookOpenText, CalendarRange } from 'lucide-react'
import { Breadcrumbs, FavoriteButton, NotePanel, ReferencePills, SectionHeading } from '../components/Shared'
import { events, getBook, getPeriod, persons } from '../repositories/catalogRepository'
import { historyService } from '../services/historyService'
import { formatYear } from '../utils/dates'
import NotFoundPage from './NotFoundPage'

export default function BookPage() {
  const { slug = '' } = useParams()
  const book = getBook(slug)
  useEffect(() => { if (book) historyService.record({ type: 'book', id: book.id, slug: book.slug, title: book.title, href: `/livro/${book.slug}` }) }, [book])
  if (!book) return <NotFoundPage />
  const period = getPeriod(book.periodId)
  const relatedPeople = book.personIds.map((id) => persons.find((person) => person.id === id)).filter((person) => person !== undefined)
  const relatedEvents = events.filter((event) => event.personIds.some((id) => book.personIds.includes(id))).slice(0, 4)
  return <article className="detail-page"><Breadcrumbs items={[{ label: 'Início', href: '/' }, { label: 'Explorar?tab=livros', href: '/explorar?tab=livros' }, { label: book.title }]} /><header className="book-hero detail-hero"><div className="book-cover"><div className="book-cover-inner"><span className="book-cover-symbol">✦</span><span className="book-cover-rule"/><strong>{book.title}</strong><small>{book.testament === 'AT' ? 'ANTIGO TESTAMENTO' : 'NOVO TESTAMENTO'}</small><span className="book-cover-seal">✧</span></div></div><div className="detail-hero-copy"><div className="detail-kicker"><span className="eyebrow">LIVRO BÍBLICO · {book.testament}</span><span className="detail-category">{book.category}</span></div><h1>{book.title}</h1><p className="detail-summary">{book.description}</p><div className="book-hero-meta"><span><CalendarRange size={15} /> Narrativa: {formatYear(book.narrativeStartYear)} a {formatYear(book.narrativeEndYear)}</span><span><BookOpenText size={15} /> {period?.shortTitle}</span></div><div className="detail-actions"><Link to={`/linha-do-tempo?period=${book.periodId}`} className="button button-dark">Ver contexto histórico <ArrowRight size={16} /></Link><FavoriteButton type="book" id={book.id} label="Salvar" /></div></div></header>
    <div className="detail-layout"><div className="detail-main-column"><section className="content-card"><SectionHeading eyebrow="VISÃO GERAL" title="Sobre o livro" /><p className="body-copy">{book.description}</p><div className="book-narrative-note"><CalendarRange size={17} /><div><strong>Período narrado</strong><p>Este livro está relacionado a acontecimentos entre {formatYear(book.narrativeStartYear)} e {formatYear(book.narrativeEndYear)}.</p></div></div><div className="book-narrative-note composition-note"><BookOpenText size={17} /><div><strong>Composição</strong><p>{book.compositionLabel ?? 'A data de composição é diferente do período narrado e pode ser debatida.'}</p></div></div></section><section className="content-card"><SectionHeading eyebrow="TEXTOS" title="Referências bíblicas" /><ReferencePills references={book.references} /></section>{relatedPeople.length > 0 && <section className="content-card"><SectionHeading eyebrow="PERSONAGENS" title="Pessoas associadas" /><div className="detail-entity-grid">{relatedPeople.map((person) => <Link key={person.id} to={`/personagem/${person.slug}`} className="person-mini-card"><span className="person-avatar">{person.title.charAt(0)}</span><span><strong>{person.title}</strong><small>{person.role}</small></span><ArrowRight size={15} /></Link>)}</div></section>}{relatedEvents.length > 0 && <section className="content-card"><SectionHeading eyebrow="CRONOLOGIA" title="Acontecimentos relacionados" /><div className="related-event-list">{relatedEvents.map((event) => <Link key={event.id} to={`/evento/${event.slug}`} className="related-event-item"><span className="related-year">{event.dateLabel}</span><span><strong>{event.title}</strong><small>{event.shortDescription}</small></span><ArrowRight size={16} /></Link>)}</div></section>}</div><aside className="detail-side-column"><div className="side-info-card"><span className="eyebrow">FICHA DO LIVRO</span><h3>{book.title}</h3><p>{book.category}</p><div className="side-divider"/><div className="side-meta-row"><span>Testamento</span><strong>{book.testament === 'AT' ? 'Antigo' : 'Novo'}</strong></div><div className="side-meta-row"><span>Período narrado</span><strong>{period?.shortTitle}</strong></div><div className="side-meta-row"><span>Composição</span><strong>Consultar nota</strong></div></div><NotePanel type="book" entityId={book.id} /><div className="side-study-note"><BookOpenText size={17} /><p>O período narrado indica quando os acontecimentos descritos se passam; a composição se refere a quando o livro tomou sua forma literária.</p></div></aside></div>
  </article>
}
