import { useState } from 'react'
import { Link } from 'react-router'
import { ArrowRight, GitCompareArrows, Plus, X } from 'lucide-react'
import { Breadcrumbs, DateBadge, SectionHeading } from '../components/Shared'
import { events, persons } from '../repositories/catalogRepository'
import { formatYear, timelinePercent } from '../utils/dates'

const COLORS = ['#a36b37', '#527e75', '#79709a']
export default function ComparePage() {
  const [selectedIds, setSelectedIds] = useState<string[]>(['samuel', 'saul', 'david'])
  const selected = selectedIds.map((id) => persons.find((person) => person.id === id)).filter((person) => person !== undefined)
  const min = Math.min(...selected.map((person) => person.birthYear), -1100)
  const max = Math.max(...selected.map((person) => person.deathYear ?? person.startYear), -950)
  const addPerson = (id: string) => { if (id && !selectedIds.includes(id) && selectedIds.length < 3) setSelectedIds([...selectedIds, id]) }
  const removePerson = (id: string) => setSelectedIds(selectedIds.filter((item) => item !== id))
  const sharedEvents = events.filter((event) => selected.length > 1 && selected.every((person) => person.eventIds.includes(event.id)))

  return <div className="compare-page">
    <Breadcrumbs items={[{ label: 'Início', href: '/' }, { label: 'Comparar' }]} />
    <div className="page-title-row"><div><span className="eyebrow">ESTUDO COMPARATIVO</span><h1>Compare personagens</h1><p>Veja as vidas lado a lado e descubra quem viveu no mesmo período.</p></div><span className="compare-title-icon"><GitCompareArrows size={23} /></span></div>
    <section className="compare-card"><div className="compare-card-header"><div><span className="eyebrow">SELECIONE ATÉ TRÊS</span><h2>Personagens da comparação</h2></div><span className="compare-counter">{selected.length} / 3</span></div><div className="selected-people">{selected.map((person) => <div key={person.id} className="selected-person" style={{ '--person-color': COLORS[selectedIds.indexOf(person.id)] } as React.CSSProperties}><span className="person-avatar">{person.title.charAt(0)}</span><span><strong>{person.title}</strong><small>{person.role}</small></span><button aria-label={`Remover ${person.title}`} onClick={() => removePerson(person.id)}><X size={15} /></button></div>)}{selected.length < 3 && <label className="add-person-select"><span className="add-person-icon"><Plus size={17} /></span><select aria-label="Adicionar personagem" value="" onChange={(event) => addPerson(event.target.value)}><option value="">Adicionar personagem</option>{persons.filter((person) => !selectedIds.includes(person.id)).map((person) => <option key={person.id} value={person.id}>{person.title} · {person.role}</option>)}</select></label>}</div>
      <div className="compare-chart"><div className="compare-chart-heading"><span className="eyebrow">FAIXAS DE VIDA ESTIMADAS</span><span>Tempo →</span></div><div className="compare-axis">{axisYears(min, max).map((year, index) => <span key={`${year}-${index}`} style={{ left: `${timelinePercent(year, min, max)}%` }}>{year === 0 ? '1 a.C./1 d.C.' : formatYear(year)}</span>)}</div>{selected.map((person) => { const start = timelinePercent(person.birthYear, min, max); const end = timelinePercent(person.deathYear ?? person.startYear, min, max); const color = COLORS[selectedIds.indexOf(person.id)]; return <div key={person.id} className="compare-life-row"><Link to={`/personagem/${person.slug}`} className="compare-person-name"><span style={{ backgroundColor: color }} />{person.title}</Link><div className="compare-life-track"><div className="compare-life-band" style={{ left: `${start}%`, width: `${Math.max(1.5, end - start)}%`, backgroundColor: color }}><i /><i /></div></div><span className="compare-life-label">{person.dateLabel}</span></div>})}<div className="compare-chart-foot">Datas de vida ilustrativas; a posição serve para comparar sobreposições aproximadas.</div></div>
    </section>
    <section className="compare-detail-section"><SectionHeading eyebrow="SÍNTESE" title="Lado a lado" description="Informações organizadas para facilitar a comparação." /><div className="compare-table-wrap"><table className="compare-table"><thead><tr><th>Aspecto</th>{selected.map((person) => <th key={person.id}><Link to={`/personagem/${person.slug}`}>{person.title}</Link></th>)}</tr></thead><tbody><tr><th>Período de vida</th>{selected.map((person) => <td key={person.id}><DateBadge label={person.dateLabel} type={person.dateType} /></td>)}</tr><tr><th>Função</th>{selected.map((person) => <td key={person.id}>{person.role}</td>)}</tr><tr><th>Referências</th>{selected.map((person) => <td key={person.id}>{person.references.slice(0, 2).map((reference) => <span key={reference.label} className="table-reference">{reference.label}</span>)}</td>)}</tr><tr><th>Acontecimentos associados</th>{selected.map((person) => <td key={person.id}>{person.eventIds.map((id) => events.find((event) => event.id === id)?.title).filter(Boolean).slice(0, 3).join(' · ') || '—'}</td>)}</tr></tbody></table></div><div className="mobile-compare-cards">{selected.map((person) => <article key={person.id} className="mobile-compare-card"><h3><Link to={`/personagem/${person.slug}`}>{person.title}</Link></h3><dl><div><dt>Período de vida</dt><dd><DateBadge label={person.dateLabel} type={person.dateType} /></dd></div><div><dt>Função</dt><dd>{person.role}</dd></div><div><dt>Referências</dt><dd>{person.references.slice(0, 2).map((reference) => reference.label).join(" · ") || "—"}</dd></div><div><dt>Acontecimentos</dt><dd>{person.eventIds.map((id) => events.find((event) => event.id === id)?.title).filter(Boolean).slice(0, 3).join(" · ") || "—"}</dd></div></dl></article>)}</div></section>
    <section className="shared-context-card"><span className="shared-context-icon"><GitCompareArrows size={19} /></span><div><span className="eyebrow">EVENTOS EM COMUM</span><h2>{sharedEvents.length ? 'Acontecimentos compartilhados' : 'Compare os períodos e as conexões'}</h2><p>{sharedEvents.length ? 'Estes acontecimentos estão associados a todas as pessoas selecionadas.' : 'A amostra inicial destaca sobreposições cronológicas. Selecione personagens relacionados para aprofundar.'}</p>{sharedEvents.map((event) => <Link key={event.id} to={`/evento/${event.slug}`} className="shared-event-link">{event.title}<ArrowRight size={14} /></Link>)}</div></section>
  </div>
}

function axisYears(min: number, max: number): number[] {
  return Array.from({ length: 5 }, (_, index) => Math.round(min + ((max - min) * index) / 4))
}
