import { Link, useParams } from 'react-router'
import { ArrowRight, MapPin } from 'lucide-react'
import { Breadcrumbs, FavoriteButton, NotePanel, ReferencePills, SectionHeading } from '../components/Shared'
import { events, getPlace, persons } from '../repositories/catalogRepository'
import NotFoundPage from './NotFoundPage'

export default function PlacePage() {
  const { slug = '' } = useParams()
  const place = getPlace(slug)
  if (!place) return <NotFoundPage />
  const linkedEvents = events.filter((event) => event.placeIds.includes(place.id))
  const linkedPeople = persons.filter((person) => person.placeIds.includes(place.id))
  return <article className="detail-page"><Breadcrumbs items={[{ label: 'Início', href: '/' }, { label: 'Explorar', href: '/explorar?tab=lugares' }, { label: place.title }]} /><header className="place-hero detail-hero"><div className="place-map-art"><div className="map-contour contour-one"/><div className="map-contour contour-two"/><div className="map-contour contour-three"/><span className="map-pin-large"><MapPin size={28} fill="currentColor" /></span><span className="map-art-caption">LUGAR NA NARRATIVA BÍBLICA</span></div><div className="detail-hero-copy"><div className="detail-kicker"><span className="eyebrow">LUGAR BÍBLICO</span></div><h1>{place.title}</h1><p className="detail-summary">{place.shortDescription}</p><div className="detail-actions"><Link to={`/linha-do-tempo`} className="button button-dark">Ver cronologia <ArrowRight size={16} /></Link><FavoriteButton type="place" id={place.id} label="Salvar" /></div></div></header><div className="detail-layout"><div className="detail-main-column"><section className="content-card"><SectionHeading eyebrow="GEOGRAFIA E CONTEXTO" title="Sobre o lugar" /><p className="body-copy">{place.description}</p><div className="location-disclaimer"><MapPin size={16} /><p>Mapa detalhado será incluído em uma próxima etapa. Esta versão usa apenas a relação textual do lugar com acontecimentos bíblicos.</p></div></section><section className="content-card"><SectionHeading eyebrow="TEXTO BÍBLICO" title="Referências" /><ReferencePills references={place.references} /></section>{linkedEvents.length > 0 && <section className="content-card"><SectionHeading eyebrow="ACONTECIMENTOS" title="Eventos neste lugar" /><div className="related-event-list">{linkedEvents.map((event) => <Link key={event.id} to={`/evento/${event.slug}`} className="related-event-item"><span className="related-year">{event.dateLabel}</span><span><strong>{event.title}</strong><small>{event.shortDescription}</small></span><ArrowRight size={16} /></Link>)}</div></section>}{linkedPeople.length > 0 && <section className="content-card"><SectionHeading eyebrow="PESSOAS" title="Personagens relacionados" /><div className="detail-entity-grid">{linkedPeople.map((person) => <Link key={person.id} to={`/personagem/${person.slug}`} className="person-mini-card"><span className="person-avatar">{person.title.charAt(0)}</span><span><strong>{person.title}</strong><small>{person.role}</small></span><ArrowRight size={15} /></Link>)}</div></section>}</div><aside className="detail-side-column"><div className="side-info-card"><span className="eyebrow">LUGAR</span><h3>{place.title}</h3><p>{place.shortDescription}</p><div className="side-divider"/><div className="side-meta-row"><span>Acontecimentos</span><strong>{linkedEvents.length}</strong></div><div className="side-meta-row"><span>Personagens</span><strong>{linkedPeople.length}</strong></div></div><NotePanel type="place" entityId={place.id} /></aside></div></article>
}
